zookeeper:
  image: confluent/zookeeper:3.4.6-cp1
  hostname: zookeeper
  ports:
    - '2181:2181'

kafka:
  image: confluent/kafka:0.9.0.0-cp1
  hostname: kafka
  ports:
    - '9092:9092'
  links:
    - zookeeper
  environment:
    - KAFKA_ADVERTISED_HOST_NAME=
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_LOG_CLEANUP_POLICY=compact

postgres:
  image: confluent/postgres-bw:0.1
  hostname: postgres
  ports:
    - '5432:5432'

bottledwater:
  image: marcusthebrown/bottledwater-json
  hostname: bottledwater
  command: --output-format=json --allow-unkeyed
  links:
    - postgres
    - kafka
  environment:
    - DB_NAME=spacon

nginx:
  image: jwilder/nginx-proxy
  ports:
    - '80:80'
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

mosquitto:
  image: jllopis/mosquitto:v1.4.8
  hostname: mosquitto
  ports:
    - '1883:1883'
    - '9883:9883'

spatialconnect-server:
  build: .
  command: npm start
  ports:
    - '8085:8085'
  links:
    - zookeeper
    - kafka
    - postgres
    - nginx
  environment:
    - PGHOST=postgres
    - PGUSER=postgres
    - PGDATABASE=postgres
    - VIRTUAL_HOST=spatialconnect-server
    - NODE_ENV=development

kafka-tools:
  image: confluent/tools:0.9.0.0-cp1
  links:
    - zookeeper
    - kafka
